<a href="https://colab.research.google.com/github/PhamThanhH/deep_learning/blob/main/Buoi1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import tensorflow as tf
import numpy as np

In [4]:
import torch
print('GPU co san khong', torch.cuda.is_available())
print('Phien ban pytorch', torch.__version__)

if torch.cuda.is_available():
    print('So luong GPU co san', torch.cuda.device_count())
    print('Device dang dung', torch.cuda.current_device())
    print('Ten GPU dang dung', torch.cuda.get_device_name(0))
    print(f'Bo nho cap phat: {torch.cuda.memory_allocated() / 1e6:.2f} MB')
    print(f'Bo nho con lai: {torch.cuda.memory_reserved() / 1e6:/2f} MB')
else:
  print('Khong co GPU')

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(device)

GPU co san khong False
Phien ban pytorch 2.10.0+cpu
Khong co GPU
cpu


In [5]:
#Bai 1
tensor1 = tf.zeros([2,3])
print(tensor1)

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)


In [6]:
#Bai 2
X = tf.constant([[1,2,3], [4,5,6]])
tensor = tf.zeros_like(X)
print(tensor)

tf.Tensor(
[[0 0 0]
 [0 0 0]], shape=(2, 3), dtype=int32)


In [7]:
#Bai 3
tensor = tf.fill([3,2], 5)
print(tensor)

tf.Tensor(
[[5 5]
 [5 5]
 [5 5]], shape=(3, 2), dtype=int32)


In [9]:
#Bai 4
base = tf.constant([6, 8, 10])
tensor = tf.tile(base, [17])[:50]
print(tensor)

tf.Tensor(
[ 6  8 10  6  8 10  6  8 10  6  8 10  6  8 10  6  8 10  6  8 10  6  8 10
  6  8 10  6  8 10  6  8 10  6  8 10  6  8 10  6  8 10  6  8 10  6  8 10
  6  8], shape=(50,), dtype=int32)


In [10]:
#Bai 5
tensor = tf.range(10, 101, 2)
print(tensor)

tf.Tensor(
[ 10  12  14  16  18  20  22  24  26  28  30  32  34  36  38  40  42  44
  46  48  50  52  54  56  58  60  62  64  66  68  70  72  74  76  78  80
  82  84  86  88  90  92  94  96  98 100], shape=(46,), dtype=int32)


In [15]:
#Bai 6
tensor = tf.random.normal(shape = [2,3], mean = 0, stddev = 2)
print(tensor)

tf.Tensor(
[[ 2.8728878  0.9892552 -2.0959394]
 [ 1.6398256 -2.497716   0.9691362]], shape=(2, 3), dtype=float32)


In [11]:
#Bai 7
tensor = tf.random.uniform(shape = [3,2], minval = 0, maxval = 2)
print(tensor)

tf.Tensor(
[[0.99272966 1.3809345 ]
 [1.417691   0.56734395]
 [1.072643   0.5557351 ]], shape=(3, 2), dtype=float32)


In [12]:
#Bai 8
tensor=tf.constant([[1,2], [3,4], [5,6]])
shuffled = tf.random.shuffle(tensor)
print(shuffled)

tf.Tensor(
[[5 6]
 [1 2]
 [3 4]], shape=(3, 2), dtype=int32)


In [14]:
#Bai 9
X = tf.random.uniform(shape=[10, 10, 3])
cropped = tf.image.random_crop(X, size=[5, 5, 3])
print(cropped.shape)

(5, 5, 3)


In [16]:
#Bai 10
x = tf.random.uniform(shape=[5], minval=0, maxval=10, dtype=tf.int32)
y = tf.random.uniform(shape=[5], minval=0, maxval=10, dtype=tf.int32)
result = tf.where(x < y, x + y, x - y)
print("x:", x.numpy())
print("y:", y.numpy())
print("result:", result.numpy())

x: [4 7 1 6 0]
y: [5 8 0 7 6]
result: [ 9 15  1 13  6]


In [19]:
#Bai 11
x = tf.random.uniform(shape=[3,2], minval=5, maxval=10, dtype=tf.int32)
y = tf.random.uniform(shape=[2,3], minval=15, maxval=20, dtype=tf.int32)
diag_mask = tf.constant([
    [1,0],
    [0,1],
    [0,0]
], dtype=tf.int32)
x_diag = x * diag_mask
y_resized = tf.transpose(y)
result = x_diag + y_resized
print("x:", x.numpy())
print("y:", y.numpy())
print("x sau khi giu đuong cheo:\n", x_diag.numpy())
print("result:\n", result.numpy())

x: [[6 7]
 [6 7]
 [9 9]]
y: [[19 15 18]
 [19 19 15]]
x sau khi giu đuong cheo:
 [[6 0]
 [0 7]
 [0 0]]
result:
 [[25 19]
 [15 26]
 [18 15]]


In [ ]:
# pandas & numpy

In [20]:
#Bai 1
arr = np.random.randint(0, 21, size=(3,3))
print(arr)
check = np.all(arr!=0)
print('Tat ca cac phan tu khac 0: ', check)

[[20 16  8]
 [18  7 10]
 [ 8 20 20]]
Tat ca cac phan tu khac 0:  True


In [21]:
#Bai 2
arr = np.random.randint(0, 21, size=(3,3))
print(arr)
check = np.any(arr!=0)
print('1 phan tu khac 0: ', check)

[[ 5  4  4]
 [15 18  2]
 [ 8  1  7]]
1 phan tu khac 0:  True


In [22]:
#Bai 3
a = np.array([1, 5, 3, 8])
b = np.array([2, 4, 3, 10])
print("a:", a)
print("b:", b)
print("a > b :", np.greater(a, b))
print("a >= b:", np.greater_equal(a, b))
print("a < b :", np.less(a, b))
print("a <= b:", np.less_equal(a, b))

a: [1 5 3 8]
b: [ 2  4  3 10]
a > b : [False  True False False]
a >= b: [False  True  True False]
a < b : [ True False False  True]
a <= b: [ True False  True  True]


In [23]:
#Bai 4
arr = np.concatenate([
    np.ones(10, dtype=int),
    np.zeros(10, dtype=int),
    np.full(10, 5)
])
print(arr)

[1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 5 5 5 5 5 5 5 5 5 5]


In [24]:
#Bai 5
arr = np.arange(30,71,2)
print(arr)

[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


In [25]:
#Bai 6
I = np.identity(3)
print(I)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [31]:
#Bai 7
arr = np.linspace(15, 55, 10, dtype=int)
print("Mảng ban đầu:", arr)
print("Bỏ phần tử đầu và cuối:", arr[1:-1])

Mảng ban đầu: [15 19 23 28 32 37 41 46 50 55]
Bỏ phần tử đầu và cuối: [19 23 28 32 37 41 46 50]


In [32]:
#Bai 8
arr = np.random.randint(0,21,size=20)
print(arr)
arr[(arr >= 9) & (arr <= 15)] *= -1
print(arr)

[ 1 19  2 16 10  0 13  2 12  4 11 11 15 20 10  0  1 12 18  6]
[  1  19   2  16 -10   0 -13   2 -12   4 -11 -11 -15  20 -10   0   1 -12
  18   6]


In [33]:
#Bai 9
matrix = np.random.randint(10, 22, size=(3, 4))
print(matrix)

[[19 21 19 14]
 [19 13 14 21]
 [18 18 18 19]]


In [ ]:
#Bai 10
matrix = np.zeros((10, 10), dtype=int)
matrix[0, :] = 1
matrix[-1, :] = 1
matrix[:, 0] = 1
matrix[:, -1] = 1
print(matrix)